ALTER TABLE materias
  ADD COLUMN IF NOT EXISTS repeticion TEXT NOT NULL DEFAULT 'semanal',
  ADD COLUMN IF NOT EXISTS fecha_inicio DATE,
  ADD COLUMN IF NOT EXISTS fecha_fin DATE,
  ADD COLUMN IF NOT EXISTS dias_dictado TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS hora_desde TEXT,
  ADD COLUMN IF NOT EXISTS hora_hasta TEXT;
